### ISSUE TITLE
[CLEANUP] script generated DEFINE names

### ISSUE THREAD

**Issue by Ikcelaks** [Ikcelaks/qmk_sequence_transform#55]
The define names generated by the script need to match our current vocabulary and naming conventions.

**Comment by kamih** [comment]
Defines rename suggestions:

SPECIAL_KEY_TRIECODE_0 -> TRIE_SEQ_TOKEN_KEY0
SEQUENCE_TRANSFORM_COUNT -> SEQ_TOKEN_COUNT
SEQUENCE_MIN_LENGTH -> SEQ_MIN_LEN
SEQUENCE_MAX_LENGTH -> SEQ_MAX_LEN
COMPLETION_MAX_LENGTH -> COMPLETION_MAX_LEN

Do we want to rename these two?
DICTIONARY_SIZE
COMPLETIONS_SIZE

**Comment by Ikcelaks** [comment]
Here are the defines I used. I forgot you had added suggestions in a comment to this issue. I chose not to abbreviate words for (except MAX and MIN), because these defines are not used frequently in the code, and I like the clarity of the full non-abbreviated words. However, I do think `TRIECODE_SEQUENCE_TOKEN_0` is a better name. So I will change that.

```
#define SEQUENCE_TOKEN_TRIECODE_0 0x0100
#define SEQUENCE_MIN_LENGTH 1 // "👍"
#define SEQUENCE_MAX_LENGTH 7 // "⎵s👍q⎵o⎵"
#define TRANSFORM_MAX_LEN 19 // "sequence⎵transform⎵"
#define COMPLETION_MAX_LENGTH 11
#define MAX_BACKSPACES 5
#define SEQUENCE_TRIE_SIZE 2346
#define COMPLETIONS_SIZE 808
#define SEQUENCE_TOKEN_COUNT 4
