### ISSUE TITLE
[CLEANUP] Create debug/log functions

### ISSUE THREAD

**Issue by Ikcelaks** [Ikcelaks/qmk_sequence_transform#58]
We should standardize to using standard functions that print debug information when the correct defines are present without dirtying up the calling function with `#ifdef`

**Comment by kamih** [comment]
Right now we have some code that prints to console if `SEQUENCE_TRANSFORM_LOG_GENERAL`, and some random uprintfs everywhere used for debugging. The `#ifdef` should be moved inside the logging function itself to make our code more readable.

And we should clearly separate things we want to always log to console if that define is enabled, from debug prints we only want to see while debugging certain features. We shouldn't have to go hunting for the `uprintf` calls we want to uncomment for this every time, so these should be replaced with special `st_debug` calls.

We can look at QMK's `quantum/logging/debug.h` for inspiration.
