### ISSUE TITLE
[CLEANUP] Change Feature Enable / Disable defines to use True / False

### ISSUE THREAD

**Issue by Ikcelaks** [Ikcelaks/qmk_sequence_transform#60]
Currently some Features are explicitly enabled by a `SEQUENCE_TRANSFORM_..._ENABLE` define, and others are enabled by default and explicitly disabled by a `SEQUENCE_TRANSFORM_..._DISABLE` define,

We should instead standardize on `SEQUENCE_TRANSFORM_..._ENABLE` as the name, and Check for true and false.

**Comment by kamih** [comment]
Do we want to put all our default feature/option define values in a new `st_defines.h`?
For example, this would include:
```
#ifndef SEQUENCE_TRANSFORM_RULE_SEARCH_MAX_SKIP
#define SEQUENCE_TRANSFORM_RULE_SEARCH_MAX_SKIP 4
#endif
```
Our .c files would include this first. (I don't think this belongs in qmk_wrapper.h cause these are not QMK related.)
If user wants to use different values, they can set those in their config.h, which gets picked up before everything else in build process.
