### ISSUE TITLE
[CLEANUP] config.json param renaming

### ISSUE THREAD

**Issue by kamih** [Ikcelaks/qmk_sequence_transform#61]
Config param rename suggestions:

Don't use 'char'. This could be confusing since these are utf8 encoded strings
where one symbol can take up to 4 bytes (while the poorly named C 'char' type takes 1 byte).
Use 'symbol' instead.

magic_chars -> sequence_token_symbols or sequence_tokens
wordbreak_char -> wordbreak_symbol
output_func_chars -> transform_func_symbols
separator_str -> separator_symbol
comment_str -> (Ok I think)

**Comment by QRiary** [comment]
I'm not entirely agree as `separator_str ` is actually a string, it can be as long as you want, for example `->` is legit separator, despite being two chars long

**Comment by Ikcelaks** [comment]
I agree with kekos. I like all of the other suggestions, but `separator_str` should remain as is.

I will do these renamed when I clean up the generator names tomorrow.
