### ISSUE TITLE
[BUG] Incorrect rule search

### ISSUE THREAD

**Issue by QRiary** [Ikcelaks/qmk_sequence_transform#68]
That's a very tricky bug, but with such rule system, `⎵equa☆y` and `⎵equa☆t` simply don't work, but `⎵equaly` and `⎵equalt` - works
```
q[aoei]       ⇒ qu\1

⎵equa☆        ⇒ equal
⎵equa☆y       ⇒ equally
⎵equa☆t       ⇒ equality
```
I have no idea what causes that, and that's not the first-priority ofc, but definitely should be fixed

**Comment by Ikcelaks** [comment]
You need to rewrite your compound rules so that they aren't relying on the virtual output buffer.
```
q[aoei]       ⇒ qu\1

⎵eqa☆        ⇒ equal
⎵eqa☆y       ⇒ equally
⎵eqa☆t       ⇒ equality```
